apiVersion: apps/v1
kind: Deployment
metadata:
  name: scality-s3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scality-s3
  template:
    metadata:
      labels:
        app: scality-s3
    spec:
      containers:
      - name: s3server
        image: scality/s3server:latest
        ports:
        - containerPort: 8000
        env:
        - name: S3DATAPATH
          value: "/data"
---
apiVersion: v1
kind: Service
metadata:
  name: scality-s3
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: scality-s3
