# clusters/dev/helmreleases/raycluster.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: raycluster
  namespace: default
spec:
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./helm/ray-cluster  # Path relative to GitRepository root
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  valuesFiles:
    - ./values.yaml  # Relative path from the HelmRelease file