# clusters/dev/helmreleases/raycluster.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: raycluster
  namespace: ray-system
spec:
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./helm/ray-cluster  # Path relative to GitRepository root
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  valuesFrom:
  - kind: ConfigMap
    name: raycluster-values
    valuesKey: values.yaml
    targetPath: ""  # Load entire values.yaml
  # Optional inline values override ConfigMap
  values:
    worker:
      minReplicas: 1
      maxReplicas: 5